version: "3.8"

services:
  wakeword:
    image: rhasspy/wyoming-openwakeword
    container_name: wakeword
    networks:
      - wyoming-network
    ports:
      - "10400:10400"
    restart: unless-stopped
    command:
      - "--preload-model"
      - "ok_nabu"

  satellite:
    image: sker65/wyoming-satellite
    container_name: satellite
    networks:
      - wyoming-network
    ports:
      - "10700:10700"
    devices:
      - "/dev/snd:/dev/snd"
    group_add:
      - audio
    volumes:
      - "$PWD/wake-detected.wav:/wake-detected.wav"
      - "$PWD/start-speaking.wav:/start-speaking.wav"
    restart: unless-stopped
    command:
      - "--name"
      - "my-satellite"
      - "--uri"
      - "tcp://0.0.0.0:10700"
      - "--awake-wav"
      - "/wake-detected.wav"
      - "--streaming-stop-command"
      - "aplay -D plughw:0,0 /start-speaking.wav"
      - "--mic-command"
      - "arecord -D plughw:0,0 -r 16000 -f S16_LE -t raw"
      - "--snd-command"
      - "aplay -D plughw:0,0 -r 20000 -f S16_LE -t raw" # higher -r value - higher and faster voice
      - "--wake-uri"
      - "tcp://wakeword:10400"
      - "--wake-word-name"
      - "ok_nabu"

networks:
  wyoming-network:
    driver: bridge
