version: "3.8"

services:
  whisper:
    image: rhasspy/wyoming-whisper
    container_name: whisper
    restart: unless-stopped
    ports:
      - "10300:10300"
    volumes:
      - "$HOME/whisperdata:/data"
    command:
      - "--model"
      - "small.en"
      - "--language"
      - "en"

  piper:
    image: rhasspy/wyoming-piper
    container_name: piper
    ports:
      - "10200:10200"
    volumes:
      - "$HOME/piperdata:/data"
    restart: unless-stopped
    command:
      - "--voice"
      - "en_US-amy-medium"
